<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Altering;
use Carbon\Carbon;

class AlteringSeeder extends Seeder
{
    /**
     * Seed the alterings (tailor queue) table with comprehensive Attire Lounge data.
     * 25 records across all statuses for a realistic admin view.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $records = [
            // ══════════════════════════════════════════════════════════
            //  PENDING (6 records)
            // ══════════════════════════════════════════════════════════
            [
                'order_no'              => 'ALT-2026-0401',
                'customer_name'         => 'Sok Visal',
                'mobile'                => '012 345 678',
                'delivery_address'      => 'Phnom Penh, BKK1',
                'product'               => 'Navy Slim-Fit Blazer – shorten sleeves 1.5 cm',
                'purchased_date'        => '2026-03-28',
                'tailor_pickup_date'    => '2026-03-30',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => null,
                'customer_pickup_status'=> null,
                'remark'                => 'Client prefers slightly shorter sleeve to show shirt cuff.',
                'altering_cost'         => 15.00,
                'start_date'            => '2026-03-30',
                'ready_at'              => $now->copy()->addDays(3)->setHour(14),
                'status'                => 'pending',
                'notified_at'           => null,
            ],
            [
                'order_no'              => 'ALT-2026-0402',
                'customer_name'         => 'Chea Dara',
                'mobile'                => '096 789 012',
                'delivery_address'      => null,
                'product'               => 'Charcoal Two-Button Suit Jacket – take in waist',
                'purchased_date'        => '2026-04-01',
                'tailor_pickup_date'    => '2026-04-02',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => null,
                'customer_pickup_status'=> null,
                'remark'                => 'Take in 2 cm each side at waist for slimmer silhouette.',
                'altering_cost'         => 20.00,
                'start_date'            => '2026-04-02',
                'ready_at'              => $now->copy()->addDays(5)->setHour(10),
                'status'                => 'pending',
                'notified_at'           => null,
            ],
            [
                'order_no'              => 'ALT-2026-0403',
                'customer_name'         => 'Meng Sophal',
                'mobile'                => '010 555 333',
                'delivery_address'      => 'Sen Sok, St. 1003',
                'product'               => 'White Dress Shirt – taper body & shorten hem',
                'purchased_date'        => '2026-04-02',
                'tailor_pickup_date'    => null,
                'pickup_status'         => 'Pending Pickup',
                'customer_pickup_date'  => null,
                'customer_pickup_status'=> null,
                'remark'                => 'Slim taper, keep collar and cuff untouched.',
                'altering_cost'         => 12.00,
                'start_date'            => '2026-04-03',
                'ready_at'              => $now->copy()->addDays(7)->setHour(16),
                'status'                => 'pending',
                'notified_at'           => null,
            ],
            [
                'order_no'              => 'ALT-2026-0404',
                'customer_name'         => 'Vong Makara',
                'mobile'                => '093 222 876',
                'delivery_address'      => null,
                'product'               => 'Office Professional Trousers – hem to 30"',
                'purchased_date'        => '2026-04-05',
                'tailor_pickup_date'    => null,
                'pickup_status'         => 'Pending Pickup',
                'customer_pickup_date'  => null,
                'customer_pickup_status'=> null,
                'remark'                => 'Standard hem, no cuff. Keep button flap.',
                'altering_cost'         => 10.00,
                'start_date'            => '2026-04-06',
                'ready_at'              => $now->copy()->addDays(4)->setHour(11),
                'status'                => 'pending',
                'notified_at'           => null,
            ],
            [
                'order_no'              => 'ALT-2026-0405',
                'customer_name'         => 'Ith Chanthy',
                'mobile'                => '077 543 219',
                'delivery_address'      => 'Toul Kork, St. 315',
                'product'               => 'Mocha Mousse Blazer – let out back 1 cm',
                'purchased_date'        => '2026-04-08',
                'tailor_pickup_date'    => null,
                'pickup_status'         => 'Pending Pickup',
                'customer_pickup_date'  => null,
                'customer_pickup_status'=> null,
                'remark'                => 'Client gained weight slightly. Let out center back seam only.',
                'altering_cost'         => 18.00,
                'start_date'            => '2026-04-09',
                'ready_at'              => $now->copy()->addDays(6)->setHour(13),
                'status'                => 'pending',
                'notified_at'           => null,
            ],
            [
                'order_no'              => 'ALT-2026-0406',
                'customer_name'         => 'Chan Bopha',
                'mobile'                => '012 675 890',
                'delivery_address'      => null,
                'product'               => 'Crimson Silk Tie – shorten by 5 cm',
                'purchased_date'        => '2026-04-10',
                'tailor_pickup_date'    => null,
                'pickup_status'         => 'Pending Pickup',
                'customer_pickup_date'  => null,
                'customer_pickup_status'=> null,
                'remark'                => 'Client is shorter, needs tie proportional to frame.',
                'altering_cost'         => 8.00,
                'start_date'            => '2026-04-11',
                'ready_at'              => $now->copy()->addDays(2)->setHour(9),
                'status'                => 'pending',
                'notified_at'           => null,
            ],

            // ══════════════════════════════════════════════════════════
            //  IN PROGRESS (6 records)
            // ══════════════════════════════════════════════════════════
            [
                'order_no'              => 'ALT-2026-0301',
                'customer_name'         => 'Heng Piseth',
                'mobile'                => '069 112 233',
                'delivery_address'      => null,
                'product'               => 'Mocha Mousse Linen Trousers – hem & taper leg',
                'purchased_date'        => '2026-03-20',
                'tailor_pickup_date'    => '2026-03-22',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => null,
                'customer_pickup_status'=> null,
                'remark'                => 'Taper from knee down, hem to 30" inseam.',
                'altering_cost'         => 18.00,
                'start_date'            => '2026-03-23',
                'ready_at'              => $now->copy()->addDays(1)->setHour(12),
                'status'                => 'in_progress',
                'notified_at'           => null,
            ],
            [
                'order_no'              => 'ALT-2026-0302',
                'customer_name'         => 'Ly Channara',
                'mobile'                => '077 888 999',
                'delivery_address'      => 'Toul Kork, St. 289',
                'product'               => 'Peak-Lapel Groom Tuxedo – adjust shoulders & chest',
                'purchased_date'        => '2026-03-18',
                'tailor_pickup_date'    => '2026-03-20',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => null,
                'customer_pickup_status'=> null,
                'remark'                => 'Wedding on April 20. Priority job – shoulders need narrowing 1 cm each side.',
                'altering_cost'         => 35.00,
                'start_date'            => '2026-03-21',
                'ready_at'              => $now->copy()->addDays(2)->setHour(9),
                'status'                => 'in_progress',
                'notified_at'           => null,
            ],
            [
                'order_no'              => 'ALT-2026-0303',
                'customer_name'         => 'Nuon Ratana',
                'mobile'                => '085 444 567',
                'delivery_address'      => null,
                'product'               => 'Black Wool Vest – take in back panel',
                'purchased_date'        => '2026-03-25',
                'tailor_pickup_date'    => '2026-03-27',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => null,
                'customer_pickup_status'=> null,
                'remark'                => 'Take in 3 cm at back for cleaner fit.',
                'altering_cost'         => 10.00,
                'start_date'            => '2026-03-28',
                'ready_at'              => $now->copy()->addDays(1)->setHour(15),
                'status'                => 'in_progress',
                'notified_at'           => null,
            ],
            [
                'order_no'              => 'ALT-2026-0304',
                'customer_name'         => 'Seng Kosal',
                'mobile'                => '098 123 456',
                'delivery_address'      => null,
                'product'               => 'Nomad Stretch Chinos – take up waist 1 inch',
                'purchased_date'        => '2026-03-30',
                'tailor_pickup_date'    => '2026-04-01',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => null,
                'customer_pickup_status'=> null,
                'remark'                => 'Waistband adjustment only, do not alter seat.',
                'altering_cost'         => 14.00,
                'start_date'            => '2026-04-02',
                'ready_at'              => $now->copy()->addDays(2)->setHour(14),
                'status'                => 'in_progress',
                'notified_at'           => null,
            ],
            [
                'order_no'              => 'ALT-2026-0305',
                'customer_name'         => 'Pich Samnang',
                'mobile'                => '070 876 543',
                'delivery_address'      => 'Chamkarmon, St. 63',
                'product'               => 'Executive Navy Blazer – shorten body length 2 cm',
                'purchased_date'        => '2026-04-03',
                'tailor_pickup_date'    => '2026-04-04',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => null,
                'customer_pickup_status'=> null,
                'remark'                => 'Client wants a slightly cropped look. Keep button stance.',
                'altering_cost'         => 22.00,
                'start_date'            => '2026-04-05',
                'ready_at'              => $now->copy()->addDays(3)->setHour(10),
                'status'                => 'in_progress',
                'notified_at'           => null,
            ],
            [
                'order_no'              => 'ALT-2026-0306',
                'customer_name'         => 'Kim Veasna',
                'mobile'                => '016 987 654',
                'delivery_address'      => null,
                'product'               => 'French-Cuff Dress Shirt – widen collar half size',
                'purchased_date'        => '2026-04-06',
                'tailor_pickup_date'    => '2026-04-07',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => null,
                'customer_pickup_status'=> null,
                'remark'                => 'Collar too tight. Open by 0.5 cm without changing band shape.',
                'altering_cost'         => 12.00,
                'start_date'            => '2026-04-08',
                'ready_at'              => $now->copy()->addDays(1)->setHour(11),
                'status'                => 'in_progress',
                'notified_at'           => null,
            ],

            // ══════════════════════════════════════════════════════════
            //  READY FOR PICKUP (5 records)
            // ══════════════════════════════════════════════════════════
            [
                'order_no'              => 'ALT-2026-0201',
                'customer_name'         => 'Keo Vannak',
                'mobile'                => '098 222 111',
                'delivery_address'      => null,
                'product'               => 'Havana Linen Shirt – shorten body length',
                'purchased_date'        => '2026-03-10',
                'tailor_pickup_date'    => '2026-03-12',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => null,
                'customer_pickup_status'=> 'Awaiting Customer',
                'remark'                => 'Shortened by 3 cm. Ready for final check.',
                'altering_cost'         => 8.00,
                'start_date'            => '2026-03-13',
                'ready_at'              => $now->copy()->subDays(2)->setHour(10),
                'status'                => 'ready',
                'notified_at'           => $now->copy()->subDays(2)->setHour(11),
            ],
            [
                'order_no'              => 'ALT-2026-0202',
                'customer_name'         => 'Tep Sokhom',
                'mobile'                => '070 333 444',
                'delivery_address'      => 'Chamkarmon, Norodom Blvd.',
                'product'               => 'Brown Italian Leather Belt – punch extra hole',
                'purchased_date'        => '2026-03-15',
                'tailor_pickup_date'    => '2026-03-16',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => null,
                'customer_pickup_status'=> 'Awaiting Customer',
                'remark'                => 'Added one extra hole. Belt conditioned.',
                'altering_cost'         => 5.00,
                'start_date'            => '2026-03-16',
                'ready_at'              => $now->copy()->subDays(1)->setHour(14),
                'status'                => 'ready',
                'notified_at'           => $now->copy()->subDays(1)->setHour(15),
            ],
            [
                'order_no'              => 'ALT-2026-0203',
                'customer_name'         => 'Yim Sothea',
                'mobile'                => '081 765 432',
                'delivery_address'      => null,
                'product'               => 'Slate Grey Business Suit Trousers – hem & take in waist',
                'purchased_date'        => '2026-03-08',
                'tailor_pickup_date'    => '2026-03-10',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => null,
                'customer_pickup_status'=> 'Awaiting Customer',
                'remark'                => 'Hem to 29", waist taken in 1 inch. Client notified via Telegram.',
                'altering_cost'         => 16.00,
                'start_date'            => '2026-03-11',
                'ready_at'              => $now->copy()->subDays(3)->setHour(16),
                'status'                => 'ready',
                'notified_at'           => $now->copy()->subDays(3)->setHour(16, 30),
            ],
            [
                'order_no'              => 'ALT-2026-0204',
                'customer_name'         => 'Khim Saroeun',
                'mobile'                => '015 654 321',
                'delivery_address'      => 'Russey Keo Market Area',
                'product'               => 'Deconstructed Linen Blazer – take in side seams',
                'purchased_date'        => '2026-03-12',
                'tailor_pickup_date'    => '2026-03-14',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => null,
                'customer_pickup_status'=> 'Awaiting Customer',
                'remark'                => 'Side seams taken in 1.5 cm. Patch pocket repositioned.',
                'altering_cost'         => 20.00,
                'start_date'            => '2026-03-15',
                'ready_at'              => $now->copy()->subDays(1)->setHour(9),
                'status'                => 'ready',
                'notified_at'           => $now->copy()->subDays(1)->setHour(9, 30),
            ],
            [
                'order_no'              => 'ALT-2026-0205',
                'customer_name'         => 'Oum Chanthol',
                'mobile'                => '069 111 222',
                'delivery_address'      => null,
                'product'               => 'Midnight Formal Suit Jacket – reposition buttons',
                'purchased_date'        => '2026-03-18',
                'tailor_pickup_date'    => '2026-03-20',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => null,
                'customer_pickup_status'=> 'Awaiting Customer',
                'remark'                => 'Moved front buttons 1 cm lower for better closing stance.',
                'altering_cost'         => 12.00,
                'start_date'            => '2026-03-21',
                'ready_at'              => $now->copy()->subHours(6),
                'status'                => 'ready',
                'notified_at'           => $now->copy()->subHours(5),
            ],

            // ══════════════════════════════════════════════════════════
            //  COMPLETED (8 records)
            // ══════════════════════════════════════════════════════════
            [
                'order_no'              => 'ALT-2026-0101',
                'customer_name'         => 'Pheakarak',
                'mobile'                => '010 471 944',
                'delivery_address'      => null,
                'product'               => 'Slim-Fit Navy Suit Trousers – hem to 29"',
                'purchased_date'        => '2026-02-10',
                'tailor_pickup_date'    => '2026-02-12',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => '2026-02-18',
                'customer_pickup_status'=> 'Collected',
                'remark'                => 'Perfect fit after hemming. Client satisfied.',
                'altering_cost'         => 10.00,
                'start_date'            => '2026-02-12',
                'ready_at'              => Carbon::parse('2026-02-16 10:00:00'),
                'status'                => 'completed',
                'notified_at'           => Carbon::parse('2026-02-16 10:30:00'),
            ],
            [
                'order_no'              => 'ALT-2026-0102',
                'customer_name'         => 'Nara Raksmey',
                'mobile'                => '081 856 626',
                'delivery_address'      => null,
                'product'               => 'Double-Breasted Blazer – let out back seam 1 cm',
                'purchased_date'        => '2026-02-05',
                'tailor_pickup_date'    => '2026-02-07',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => '2026-02-14',
                'customer_pickup_status'=> 'Collected',
                'remark'                => 'VIP rush job. Completed in 5 days.',
                'altering_cost'         => 25.00,
                'start_date'            => '2026-02-07',
                'ready_at'              => Carbon::parse('2026-02-12 09:00:00'),
                'status'                => 'completed',
                'notified_at'           => Carbon::parse('2026-02-12 09:15:00'),
            ],
            [
                'order_no'              => 'ALT-2026-0103',
                'customer_name'         => 'ReakSa',
                'mobile'                => '081 333 693',
                'delivery_address'      => 'Delivery – BKK3',
                'product'               => 'Travel Collection Chino – taper & hem',
                'purchased_date'        => '2026-01-25',
                'tailor_pickup_date'    => '2026-01-27',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => '2026-02-03',
                'customer_pickup_status'=> 'Delivered',
                'remark'                => 'Delivered to home address. VIP member.',
                'altering_cost'         => 22.00,
                'start_date'            => '2026-01-28',
                'ready_at'              => Carbon::parse('2026-02-01 11:00:00'),
                'status'                => 'completed',
                'notified_at'           => Carbon::parse('2026-02-01 11:30:00'),
            ],
            [
                'order_no'              => 'ALT-2026-0104',
                'customer_name'         => 'Marnatte Kong',
                'mobile'                => '012 460 557',
                'delivery_address'      => null,
                'product'               => 'Shawl-Collar Dinner Jacket – shorten sleeves',
                'purchased_date'        => '2026-01-20',
                'tailor_pickup_date'    => '2026-01-22',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => '2026-01-28',
                'customer_pickup_status'=> 'Collected',
                'remark'                => 'Sleeve shortened 2 cm. Button repositioned.',
                'altering_cost'         => 18.00,
                'start_date'            => '2026-01-23',
                'ready_at'              => Carbon::parse('2026-01-26 14:00:00'),
                'status'                => 'completed',
                'notified_at'           => Carbon::parse('2026-01-26 14:30:00'),
            ],
            [
                'order_no'              => 'ALT-2026-0105',
                'customer_name'         => 'Kuoch Sanara',
                'mobile'                => '087 669 168',
                'delivery_address'      => null,
                'product'               => 'Groom Peak-Lapel Tuxedo – narrow shoulders 0.5 cm each',
                'purchased_date'        => '2026-01-15',
                'tailor_pickup_date'    => '2026-01-17',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => '2026-01-24',
                'customer_pickup_status'=> 'Collected',
                'remark'                => 'Shoulder adjustment completed. Client very happy with result.',
                'altering_cost'         => 30.00,
                'start_date'            => '2026-01-18',
                'ready_at'              => Carbon::parse('2026-01-22 10:00:00'),
                'status'                => 'completed',
                'notified_at'           => Carbon::parse('2026-01-22 10:15:00'),
            ],
            [
                'order_no'              => 'ALT-2026-0106',
                'customer_name'         => 'Lam Soytry',
                'mobile'                => '012 386 711',
                'delivery_address'      => null,
                'product'               => 'Havana Camp-Collar Shirt – take in side seams',
                'purchased_date'        => '2026-02-20',
                'tailor_pickup_date'    => '2026-02-22',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => '2026-02-28',
                'customer_pickup_status'=> 'Collected',
                'remark'                => 'Side seams taken in for a more fitted look.',
                'altering_cost'         => 10.00,
                'start_date'            => '2026-02-23',
                'ready_at'              => Carbon::parse('2026-02-26 15:00:00'),
                'status'                => 'completed',
                'notified_at'           => Carbon::parse('2026-02-26 15:30:00'),
            ],
            [
                'order_no'              => 'ALT-2026-0107',
                'customer_name'         => 'Sok Panha',
                'mobile'                => '012 550 033',
                'delivery_address'      => null,
                'product'               => 'Three-Piece Pinstripe Suit – adjust vest back strap',
                'purchased_date'        => '2026-03-01',
                'tailor_pickup_date'    => '2026-03-03',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => '2026-03-08',
                'customer_pickup_status'=> 'Collected',
                'remark'                => 'Vest buckle strap replaced with adjustable cinch. Returning client.',
                'altering_cost'         => 15.00,
                'start_date'            => '2026-03-04',
                'ready_at'              => Carbon::parse('2026-03-06 11:00:00'),
                'status'                => 'completed',
                'notified_at'           => Carbon::parse('2026-03-06 11:30:00'),
            ],
            [
                'order_no'              => 'ALT-2026-0108',
                'customer_name'         => 'Tim Ochasan',
                'mobile'                => '099 734 192',
                'delivery_address'      => 'Delivery – Chamkarmon',
                'product'               => 'Mocha Mousse Chinos x2 – hem both pairs',
                'purchased_date'        => '2026-03-05',
                'tailor_pickup_date'    => '2026-03-07',
                'pickup_status'         => 'Picked Up',
                'customer_pickup_date'  => '2026-03-14',
                'customer_pickup_status'=> 'Delivered',
                'remark'                => '2 pairs hemmed to 31". Delivered to office address.',
                'altering_cost'         => 20.00,
                'start_date'            => '2026-03-08',
                'ready_at'              => Carbon::parse('2026-03-12 09:00:00'),
                'status'                => 'completed',
                'notified_at'           => Carbon::parse('2026-03-12 09:30:00'),
            ],
        ];

        foreach ($records as $record) {
            Altering::updateOrCreate(
                ['order_no' => $record['order_no']],
                $record
            );
        }
    }
}
