<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CustomerProfile;
use Illuminate\Support\Facades\DB;

class CustomerProfileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Truncate existing data to avoid duplicates if re-running
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        CustomerProfile::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $data = [
            [
                "date" => "2026-01-02",
                "client_status" => "Returning",
                "name" => "Pheakarak",
                "nationality" => "Cambodian",
                "phone" => "010471944",
                "host" => "Sokleap",
                "assistant" => "Sithorn",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "30",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-02",
                "client_status" => "New",
                "name" => "Sivkhsatratep",
                "nationality" => "Cambodian",
                "phone" => "086609168",
                "host" => "Sithorn",
                "assistant" => "Sokleap",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "5XL",
                "jacket_size" => "5XL",
                "pants_size" => "40",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-03",
                "client_status" => "New",
                "name" => "Mao Sothearith",
                "nationality" => "Cambodian",
                "phone" => "098430467",
                "host" => "Lima",
                "assistant" => "Santa",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "",
                "jacket_size" => "",
                "pants_size" => "29",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-03",
                "client_status" => "Returning",
                "name" => "Lam Soytry",
                "nationality" => "Cambodian",
                "phone" => "012386711",
                "host" => "Lima",
                "assistant" => "Santa",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "S",
                "jacket_size" => "M",
                "pants_size" => "29",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-04",
                "client_status" => "Returning",
                "name" => "Meng neng",
                "nationality" => "Cambodian",
                "phone" => "0965124740",
                "host" => "Lima",
                "assistant" => "Santa",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "33",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => "change button"
            ],
            [
                "date" => "2026-01-05",
                "client_status" => "New",
                "name" => "Norak",
                "nationality" => "Cambodian",
                "phone" => "081444476",
                "host" => "Sokleap",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "XL",
                "pants_size" => "32",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => "need jean"
            ],
            [
                "date" => "2026-01-06",
                "client_status" => "New",
                "name" => "heang khut",
                "nationality" => "Cambodian",
                "phone" => "070343465",
                "host" => "Sokleap",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "M",
                "jacket_size" => "M",
                "pants_size" => "32",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-06",
                "client_status" => "New",
                "name" => "chhorrovath",
                "nationality" => "Cambodian",
                "phone" => "0965573773",
                "host" => "Lima",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "",
                "jacket_size" => "M",
                "pants_size" => "",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => "groom jk peak lapel 250$ (M) Black"
            ],
            [
                "date" => "2026-01-07",
                "client_status" => "New",
                "name" => "Ravuth",
                "nationality" => "Cambodian",
                "phone" => "0169050809",
                "host" => "Lima",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "",
                "jacket_size" => "",
                "pants_size" => "",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-07",
                "client_status" => "New",
                "name" => "Ly heng",
                "nationality" => "Cambodian",
                "phone" => "093884963",
                "host" => "Sokleap",
                "assistant" => "Chorvy",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "31",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-08",
                "client_status" => "Returning",
                "name" => "Huon lihour",
                "nationality" => "Cambodian",
                "phone" => "015920923",
                "host" => "Lima",
                "assistant" => "Santa",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "S",
                "jacket_size" => "S",
                "pants_size" => "28",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-09",
                "client_status" => "New",
                "name" => "Sary Phearun",
                "nationality" => "Cambodian",
                "phone" => "012332393",
                "host" => "Sokleap",
                "assistant" => "Sithorn",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "3XL",
                "jacket_size" => "XL",
                "pants_size" => "36",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-09",
                "client_status" => "Returning",
                "name" => "lyhour",
                "nationality" => "Cambodian",
                "phone" => "098730573",
                "host" => "Sokleap",
                "assistant" => "Sithorn",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "XL",
                "jacket_size" => "XL",
                "pants_size" => "31",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-10",
                "client_status" => "New",
                "name" => "Vathanak",
                "nationality" => "Cambodian",
                "phone" => "099827827",
                "host" => "Sokleap",
                "assistant" => "Chorvy",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "M",
                "jacket_size" => "M",
                "pants_size" => "32",
                "shoes_size" => "",
                "preferred_color" => "BROWN",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-12",
                "client_status" => "New",
                "name" => "nam chheab",
                "nationality" => "Cambodian",
                "phone" => "087770276",
                "host" => "Sokleap",
                "assistant" => "Sithorn",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "M",
                "jacket_size" => "M",
                "pants_size" => "30",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-13",
                "client_status" => "New",
                "name" => "panha",
                "nationality" => "Cambodian",
                "phone" => "010806178",
                "host" => "Sithorn",
                "assistant" => "Santa",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "32",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-13",
                "client_status" => "New",
                "name" => "Soeya",
                "nationality" => "Expat",
                "phone" => "0966663361",
                "host" => "Lima",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "31",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-13",
                "client_status" => "New",
                "name" => "Eden",
                "nationality" => "Cambodian",
                "phone" => "012633368",
                "host" => "Chorvy",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "XL",
                "pants_size" => "34",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-13",
                "client_status" => "New",
                "name" => "sokun therayu",
                "nationality" => "Cambodian",
                "phone" => "077388888",
                "host" => "Sithorn",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "30",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-14",
                "client_status" => "Returning",
                "name" => "Sok Panha",
                "nationality" => "Cambodian",
                "phone" => "012550033",
                "host" => "Lima",
                "assistant" => "Sithorn",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "3XL",
                "jacket_size" => "3XL",
                "pants_size" => "32",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => "adjust jk"
            ],
            [
                "date" => "2026-01-14",
                "client_status" => "Returning",
                "name" => "Tim ochasan",
                "nationality" => "Expat",
                "phone" => "099734192",
                "host" => "Lima",
                "assistant" => "Santa",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "",
                "jacket_size" => "",
                "pants_size" => "34",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-14",
                "client_status" => "VIP",
                "name" => "Marnatte kong",
                "nationality" => "Cambodian",
                "phone" => "012460557",
                "host" => "Sokleap",
                "assistant" => "Sithorn",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "M",
                "jacket_size" => "M",
                "pants_size" => "31",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-14",
                "client_status" => "Returning",
                "name" => "chhay Heng",
                "nationality" => "Cambodian",
                "phone" => "061372515",
                "host" => "Sokleap",
                "assistant" => "Sithorn",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "S",
                "jacket_size" => "S",
                "pants_size" => "29",
                "shoes_size" => "",
                "preferred_color" => "BROWN",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-14",
                "client_status" => "Returning",
                "name" => "raymond quintel",
                "nationality" => "Cambodian",
                "phone" => "1(415)5747105",
                "host" => "Sithorn",
                "assistant" => "Lima",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "31",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-14",
                "client_status" => "New",
                "name" => "oudom",
                "nationality" => "Cambodian",
                "phone" => "014944949",
                "host" => "Lima",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "M",
                "jacket_size" => "M",
                "pants_size" => "32",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-14",
                "client_status" => "New",
                "name" => "jason Ban",
                "nationality" => "Cambodian",
                "phone" => "017276773",
                "host" => "Lima",
                "assistant" => "Santa",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "31",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-14",
                "client_status" => "New",
                "name" => "Theareath",
                "nationality" => "Cambodian",
                "phone" => "011281111",
                "host" => "Sokleap",
                "assistant" => "Santa",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "M",
                "jacket_size" => "",
                "pants_size" => "29",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-15",
                "client_status" => "New",
                "name" => "vet makhak",
                "nationality" => "Cambodian",
                "phone" => "012260697",
                "host" => "Pingann",
                "assistant" => "Chorvy",
                "how_did_they_find_us" => "Referral",
                "shirt_size" => "XL",
                "jacket_size" => "",
                "pants_size" => "32",
                "shoes_size" => "40",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-15",
                "client_status" => "Returning",
                "name" => "Sokha puthirith Ung",
                "nationality" => "Cambodian",
                "phone" => "098664866",
                "host" => "Sokleap",
                "assistant" => "",
                "how_did_they_find_us" => "Referral",
                "shirt_size" => "XL",
                "jacket_size" => "XL",
                "pants_size" => "33",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-15",
                "client_status" => "New",
                "name" => "Sokha Ratanak Ung",
                "nationality" => "Cambodian",
                "phone" => "0979999567",
                "host" => "Chorvy",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "M",
                "jacket_size" => "M",
                "pants_size" => "29",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-16",
                "client_status" => "VIP",
                "name" => "ReakSa",
                "nationality" => "Cambodian",
                "phone" => "081333693",
                "host" => "Sokleap",
                "assistant" => "Sithorn",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "M",
                "jacket_size" => "M",
                "pants_size" => "31",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-17",
                "client_status" => "VIP",
                "name" => "Kuoch Sanara",
                "nationality" => "Cambodian",
                "phone" => "087669168",
                "host" => "Chorvy",
                "assistant" => "Sokleap",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "",
                "jacket_size" => "M",
                "pants_size" => "",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-17",
                "client_status" => "VIP",
                "name" => "Nara Raksmey",
                "nationality" => "Cambodian",
                "phone" => "081856626",
                "host" => "Sokleap",
                "assistant" => "Sithorn",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "XL",
                "jacket_size" => "2XL",
                "pants_size" => "36",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-18",
                "client_status" => "New",
                "name" => "chan Somanith",
                "nationality" => "Cambodian",
                "phone" => "085880056",
                "host" => "Sithorn",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "32",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-18",
                "client_status" => "New",
                "name" => "Van sok",
                "nationality" => "Cambodian",
                "phone" => "0889699699",
                "host" => "Sithorn",
                "assistant" => "Santa",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "XL",
                "jacket_size" => "XL",
                "pants_size" => "34",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-18",
                "client_status" => "New",
                "name" => "Thoun SokCheat",
                "nationality" => "Cambodian",
                "phone" => "070407848",
                "host" => "Sokleap",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "S",
                "jacket_size" => "M",
                "pants_size" => "29",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-18",
                "client_status" => "New",
                "name" => "Loah seagly",
                "nationality" => "Cambodian",
                "phone" => "093959259",
                "host" => "Lima",
                "assistant" => "Santa",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "XL",
                "jacket_size" => "",
                "pants_size" => "33",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-18",
                "client_status" => "New",
                "name" => "yim Sonara",
                "nationality" => "Cambodian",
                "phone" => "010711443",
                "host" => "Sithorn",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "XL",
                "jacket_size" => "XL",
                "pants_size" => "33",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-19",
                "client_status" => "New",
                "name" => "Mouy Kun",
                "nationality" => "Cambodian",
                "phone" => "069676525",
                "host" => "Sokleap",
                "assistant" => "Chorvy",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "32",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-19",
                "client_status" => "New",
                "name" => "Sunyuthyrith Moeng",
                "nationality" => "Cambodian",
                "phone" => "095963366",
                "host" => "Chorvy",
                "assistant" => "Sithorn",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "M",
                "jacket_size" => "M",
                "pants_size" => "30",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-21",
                "client_status" => "New",
                "name" => "thach sotheara",
                "nationality" => "Cambodian",
                "phone" => "090969969",
                "host" => "Sithorn",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "XL",
                "jacket_size" => "XL",
                "pants_size" => "33",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-21",
                "client_status" => "New",
                "name" => "Youeur",
                "nationality" => "Cambodian",
                "phone" => "070861996",
                "host" => "Sithorn",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "",
                "jacket_size" => "",
                "pants_size" => "33",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-22",
                "client_status" => "New",
                "name" => "Cham chakrey",
                "nationality" => "Cambodian",
                "phone" => "010307070",
                "host" => "Lima",
                "assistant" => "Santa",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "",
                "jacket_size" => "",
                "pants_size" => "42",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-23",
                "client_status" => "New",
                "name" => "Heang Senghour",
                "nationality" => "Cambodian",
                "phone" => "0967899494",
                "host" => "Lima",
                "assistant" => "Chorvy",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "",
                "jacket_size" => "",
                "pants_size" => "",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-23",
                "client_status" => "New",
                "name" => "ousa",
                "nationality" => "Cambodian",
                "phone" => "0965811133",
                "host" => "Sithorn",
                "assistant" => "Lima",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "XL",
                "jacket_size" => "XL",
                "pants_size" => "34",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-23",
                "client_status" => "New",
                "name" => "Sunyuthyrith Moeng",
                "nationality" => "Cambodian",
                "phone" => "095963366",
                "host" => "Sithorn",
                "assistant" => "Lima",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "",
                "jacket_size" => "",
                "pants_size" => "31",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-24",
                "client_status" => "VIP",
                "name" => "thavuth",
                "nationality" => "Cambodian",
                "phone" => "012731400",
                "host" => "Lima",
                "assistant" => "Sithorn",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "",
                "jacket_size" => "",
                "pants_size" => "",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-24",
                "client_status" => "VIP",
                "name" => "Sao pisey",
                "nationality" => "Cambodian",
                "phone" => "012688817",
                "host" => "Sokleap",
                "assistant" => "Sithorn",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "33",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-25",
                "client_status" => "VIP",
                "name" => "Darung",
                "nationality" => "Cambodian",
                "phone" => "010906010",
                "host" => "Lima",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "",
                "jacket_size" => "L",
                "pants_size" => "",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-25",
                "client_status" => "VIP",
                "name" => "keo vanna",
                "nationality" => "Cambodian",
                "phone" => "0974580027",
                "host" => "Lima",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "M",
                "jacket_size" => "M",
                "pants_size" => "30",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-26",
                "client_status" => "New",
                "name" => "David",
                "nationality" => "Cambodian",
                "phone" => "0967588885",
                "host" => "Sithorn",
                "assistant" => "Chorvy",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "",
                "jacket_size" => "XL",
                "pants_size" => "34",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-26",
                "client_status" => "VIP",
                "name" => "Sotra",
                "nationality" => "Cambodian",
                "phone" => "0969954255",
                "host" => "Sithorn",
                "assistant" => "Chorvy",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "M",
                "jacket_size" => "M",
                "pants_size" => "32",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-26",
                "client_status" => "New",
                "name" => "nak",
                "nationality" => "Cambodian",
                "phone" => "099911229",
                "host" => "Sokleap",
                "assistant" => "Sithorn",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "S",
                "jacket_size" => "M",
                "pants_size" => "31",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-26",
                "client_status" => "New",
                "name" => "Keo Devid",
                "nationality" => "Cambodian",
                "phone" => "078456654",
                "host" => "Lima",
                "assistant" => "Chorvy",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "30",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-27",
                "client_status" => "New",
                "name" => "Lyming buoy",
                "nationality" => "Cambodian",
                "phone" => "0962056660",
                "host" => "Lima",
                "assistant" => "Chorvy",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "30",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-27",
                "client_status" => "New",
                "name" => "Yarandy",
                "nationality" => "Cambodian",
                "phone" => "015535454",
                "host" => "Sokleap",
                "assistant" => "Chorvy",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "XL",
                "jacket_size" => "XL",
                "pants_size" => "34",
                "shoes_size" => "",
                "preferred_color" => "GREY",
                "color_notes" => "brown",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-27",
                "client_status" => "VIP",
                "name" => "Hoklay heng",
                "nationality" => "Cambodian",
                "phone" => "089278888",
                "host" => "Sokleap",
                "assistant" => "Chorvy",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "",
                "jacket_size" => "",
                "pants_size" => "32",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-28",
                "client_status" => "VIP",
                "name" => "Prom Morokot",
                "nationality" => "Cambodian",
                "phone" => "017878753",
                "host" => "Chorvy",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "",
                "jacket_size" => "M",
                "pants_size" => "29",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-29",
                "client_status" => "New",
                "name" => "Reaksmey",
                "nationality" => "Cambodian",
                "phone" => "010777667",
                "host" => "Lima",
                "assistant" => "Chorvy",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "",
                "jacket_size" => "",
                "pants_size" => "29",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-30",
                "client_status" => "VIP",
                "name" => "chansith",
                "nationality" => "Cambodian",
                "phone" => "0979097899",
                "host" => "Pingann",
                "assistant" => "Lima",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "2XL",
                "jacket_size" => "2XL",
                "pants_size" => "36",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-30",
                "client_status" => "New",
                "name" => "Meng Virak",
                "nationality" => "Cambodian",
                "phone" => "092969670",
                "host" => "Lima",
                "assistant" => "Sithorn",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "31",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-31",
                "client_status" => "New",
                "name" => "Khann Daro",
                "nationality" => "Cambodian",
                "phone" => "099744428",
                "host" => "Chorvy",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "S",
                "jacket_size" => "",
                "pants_size" => "30",
                "shoes_size" => "39",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-31",
                "client_status" => "VIP",
                "name" => "Nix",
                "nationality" => "Cambodian",
                "phone" => "081797964",
                "host" => "Sokleap",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "2XL",
                "jacket_size" => "2XL",
                "pants_size" => "36",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-31",
                "client_status" => "New",
                "name" => "koch sothearith",
                "nationality" => "Cambodian",
                "phone" => "012811337",
                "host" => "Lima",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "2XL",
                "jacket_size" => "",
                "pants_size" => "34",
                "shoes_size" => "",
                "preferred_color" => "BEIGE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-31",
                "client_status" => "New",
                "name" => "Ben",
                "nationality" => "Traveller",
                "phone" => "077895081",
                "host" => "Lima",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "XL",
                "jacket_size" => "XL",
                "pants_size" => "36",
                "shoes_size" => "",
                "preferred_color" => "BEIGE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-31",
                "client_status" => "New",
                "name" => "Sopheak",
                "nationality" => "Cambodian",
                "phone" => "077359474",
                "host" => "Sokleap",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "XS",
                "jacket_size" => "S",
                "pants_size" => "31",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => "groom"
            ],
            [
                "date" => "2026-01-31",
                "client_status" => "New",
                "name" => "Lo lyseang",
                "nationality" => "Cambodian",
                "phone" => "015666952",
                "host" => "Lima",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "29",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-31",
                "client_status" => "Returning",
                "name" => "heng sothearith",
                "nationality" => "Traveller",
                "phone" => "099575707",
                "host" => "Sithorn",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "3XL",
                "jacket_size" => "3XL",
                "pants_size" => "34",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-01-31",
                "client_status" => "Returning",
                "name" => "Chea soten",
                "nationality" => "Cambodian",
                "phone" => "070377794",
                "host" => "Lima",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "M",
                "jacket_size" => "M",
                "pants_size" => "31",
                "shoes_size" => "",
                "preferred_color" => "GREY",
                "color_notes" => "",
                "remarks" => "-"
            ],
            [
                "date" => "2026-02-01",
                "client_status" => "New",
                "name" => "KLim sela Drong",
                "nationality" => "Cambodian",
                "phone" => "095951066",
                "host" => "",
                "assistant" => "",
                "how_did_they_find_us" => "Referral",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => "-"
            ],
            [
                "date" => "2026-02-01",
                "client_status" => "New",
                "name" => "Sea",
                "nationality" => "Cambodian",
                "phone" => "011870519",
                "host" => "Sokleap",
                "assistant" => "",
                "how_did_they_find_us" => "Referral",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "32",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => "-"
            ],
            [
                "date" => "2026-02-01",
                "client_status" => "Returning",
                "name" => "Theareak",
                "nationality" => "Cambodian",
                "phone" => "011281111",
                "host" => "Sokleap",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "M",
                "jacket_size" => "M",
                "pants_size" => "30",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => "-"
            ],
            [
                "date" => "2026-02-01",
                "client_status" => "Returning",
                "name" => "Jeff steeves",
                "nationality" => "Expat",
                "phone" => "085250962",
                "host" => "Lima",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "M",
                "jacket_size" => "M",
                "pants_size" => "30",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => "-"
            ],
            [
                "date" => "2026-02-02",
                "client_status" => "Returning",
                "name" => "Sari Phearun",
                "nationality" => "Cambodian",
                "phone" => "012332393",
                "host" => "Sokleap",
                "assistant" => "",
                "how_did_they_find_us" => "",
                "shirt_size" => "",
                "jacket_size" => "",
                "pants_size" => "",
                "shoes_size" => "",
                "preferred_color" => "",
                "color_notes" => "",
                "remarks" => "-"
            ],
            [
                "date" => "2026-02-03",
                "client_status" => "Returning",
                "name" => "Roth Mongkol",
                "nationality" => "Cambodian",
                "phone" => "0314677778",
                "host" => "Lima",
                "assistant" => "Santa",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "33",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => "-"
            ],
            [
                "date" => "2026-02-03",
                "client_status" => "VIP",
                "name" => "Kosla",
                "nationality" => "Cambodian",
                "phone" => "017586581",
                "host" => "Chorvy",
                "assistant" => "",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "",
                "jacket_size" => "",
                "pants_size" => "30",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-02-04",
                "client_status" => "New",
                "name" => "Lim LyPheng",
                "nationality" => "Cambodian",
                "phone" => "016718350",
                "host" => "Lima",
                "assistant" => "Santa",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "4XL",
                "jacket_size" => "5XL",
                "pants_size" => "38",
                "shoes_size" => "43",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-02-04",
                "client_status" => "New",
                "name" => "Seila",
                "nationality" => "Cambodian",
                "phone" => "016225156",
                "host" => "Pingann",
                "assistant" => "Lima",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "L",
                "jacket_size" => "L",
                "pants_size" => "",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-02-04",
                "client_status" => "New",
                "name" => "Bradon Ham",
                "nationality" => "Cambodian",
                "phone" => "087776889",
                "host" => "Lima",
                "assistant" => "Santa",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "5XL",
                "jacket_size" => "5XL",
                "pants_size" => "40",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-02-04",
                "client_status" => "New",
                "name" => "Soknary leang",
                "nationality" => "Cambodian",
                "phone" => "012583332",
                "host" => "Pingann",
                "assistant" => "Chorvy",
                "how_did_they_find_us" => "Instagram",
                "shirt_size" => "",
                "jacket_size" => "M",
                "pants_size" => "",
                "shoes_size" => "",
                "preferred_color" => "BROWN",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-02-06",
                "client_status" => "VIP",
                "name" => "Yeeng Samdy",
                "nationality" => "Cambodian",
                "phone" => "092133346",
                "host" => "Chorvy",
                "assistant" => "Sithorn",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "",
                "jacket_size" => "3XL",
                "pants_size" => "33",
                "shoes_size" => "",
                "preferred_color" => "BROWN",
                "color_notes" => "",
                "remarks" => ""
            ],
            [
                "date" => "2026-02-07",
                "client_status" => "New",
                "name" => "Sun",
                "nationality" => "Cambodian",
                "phone" => "",
                "host" => "Lima",
                "assistant" => "Santa",
                "how_did_they_find_us" => "Facebook",
                "shirt_size" => "M",
                "jacket_size" => "M",
                "pants_size" => "30",
                "shoes_size" => "",
                "preferred_color" => "BLACK/BLUE",
                "color_notes" => "",
                "remarks" => ""
            ]
        ];

        foreach ($data as $row) {
            CustomerProfile::create($row);
        }
    }
}
