[providers]
php = "8.2"

[phases.setup]
nixPkgs = ["php82Extensions.redis", "php82Extensions.pcntl", "php82Extensions.sockets", "php82Extensions.gd", "php82Extensions.bcmath"]

[phases.build]
cmds = ["composer install --no-dev", "npm install", "npm run build"]

[processes]
web = "php artisan migrate --force && (php artisan reverb:start --host=127.0.0.1 --port=8081 &) && frankenphp run --config Caddyfile --adapter caddyfile"
